import{j as e}from"../../assets/jsx-runtime.js";import{S as s}from"./Sigil.js";import{u as c}from"../../assets/index.js";import{m as a}from"../../assets/proxy.js";import"../../data/sigils.js";const d=[{path:"/about",label:"ORIGIN",sigilId:"about",color:"cyan",angle:0},{path:"/projects",label:"WORKS",sigilId:"projects",color:"magenta",angle:60},{path:"/skills",label:"ARCANA",sigilId:"skills",color:"lime",angle:120},{path:"/writing",label:"TOMES",sigilId:"writing",color:"purple",angle:180},{path:"/case-studies",label:"REPORTS",sigilId:"case-studies",color:"cyan",angle:240},{path:"/contact",label:"SIGNAL",sigilId:"contact",color:"magenta",angle:300}],b=()=>{const r=c(),o=160;return e.jsxs("div",{className:"relative w-[300px] h-[300px] md:w-[500px] md:h-[500px] flex items-center justify-center",children:[e.jsx(a.div,{className:"absolute inset-0 rounded-full border border-neon-purple/20 border-dashed",animate:{rotate:360},transition:{duration:40,repeat:1/0,ease:"linear"}}),e.jsx(a.div,{className:"absolute inset-4 rounded-full border border-neon-cyan/10",animate:{rotate:-360},transition:{duration:30,repeat:1/0,ease:"linear"}}),e.jsx(a.div,{className:"absolute inset-12 rounded-full border-2 border-neon-magenta/5 border-dotted",animate:{rotate:360},transition:{duration:20,repeat:1/0,ease:"linear"}}),e.jsxs("div",{className:"absolute flex flex-col items-center justify-center text-center z-10",children:[e.jsx(s,{id:"home",color:"purple",size:48,animate:!0,className:"mb-4 drop-shadow-glow-purple"}),e.jsx("h1",{className:"font-display text-3xl md:text-4xl tracking-[0.2em] text-glow-purple text-neon-purple mb-2",children:"SYS.WITCH"}),e.jsx("p",{className:"font-mono text-xs text-text-secondary max-w-[200px]",children:"PORTAL OPEN. AWAITING COMMAND."})]}),e.jsx("div",{className:"absolute inset-0 hidden md:block",children:d.map(t=>{const l=(t.angle-90)*(Math.PI/180),i=Math.cos(l)*o,n=Math.sin(l)*o;return e.jsxs(a.button,{onClick:()=>r(t.path),className:"absolute top-1/2 left-1/2 w-16 h-16 -ml-8 -mt-8 flex flex-col items-center justify-center group focus:outline-none",style:{x:i,y:n},whileHover:{scale:1.2},whileTap:{scale:.9},"aria-label":`Navigate to ${t.label}`,children:[e.jsx("div",{className:`
                relative flex items-center justify-center w-12 h-12 rounded-full 
                bg-surface-elevated border border-neon-${t.color}/50 
                group-hover:border-neon-${t.color} group-hover:shadow-glow-${t.color}
                transition-all duration-300 group-focus:ring-2 group-focus:ring-neon-${t.color}
              `,children:e.jsx(s,{id:t.sigilId,color:t.color,size:24})}),e.jsx("span",{className:`
                absolute top-14 font-display text-xs tracking-widest opacity-0 group-hover:opacity-100 
                transition-opacity duration-300 text-neon-${t.color} text-glow-${t.color} whitespace-nowrap
              `,children:t.label})]},t.path)})}),e.jsx("div",{className:"absolute inset-0 flex flex-col justify-between items-center py-4 md:hidden pointer-events-none"})]})};export{b as P};
